name: ci

on:
  pull_request:
    branches: [main]
jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Install dependencies
        run: 'npm --prefix ./AdminPortal/ ci && npm --prefix ./backend/ ci && npm --prefix ./LAKMobile/ ci'
      - name: Lint ./LAKMobile
        run: npm --prefix ./LAKMobile/ run lint-check
      - name: Lint ./AdminPortal
        if: always()
        run: npm --prefix ./AdminPortal/ run lint-check
      - name: Lint ./backend
        if: always()
        run: npm --prefix ./backend/ run lint-check
